server:
  port: 9091
spring:
  application:
    name: getway

  redis:
    host: localhost
    port: 6379
    password: jl2012
    database: 0

  cloud:
    consul:
      host: 192.168.85.128  # linux
      port: 8500
      discovery: #\u6CE8\u518C\u5230consul\u7684\u670D\u52A1\u540D\u79F0
        service-name: ${spring.application.name}
        hostname: 192.168.85.128
        health-check-path: /health  # \u5065\u5EB7\u68C0\u6D4B\u7684url\uFF0C\u5982\u679C\u4E0D\u914D\u7F6E\uFF0C\u5065\u5EB7\u68C0\u6D4B\u4E00\u5B9A\u5931\u8D25
        health-check-interval: 10s   # \u5065\u5EB7\u68C0\u6D4B\u65F6\u95F4\u95F4\u9694
        heartbeat:
          enabled: true  # \u5FC3\u8DF3   \u5751\u6240\u5728\uFF0Cspringboot2.x \u8FD9\u4E2A\u4E00\u5B9A\u8981\u5F00
        prefer-ip-address: true # \u8868\u793A\u6CE8\u518C\u65F6\u4F7F\u7528IP\u800C\u4E0D\u662Fhostname

    gateway:
      routes:
        - id: host_route2
          uri: lb://provider01  #目标服务地址
          predicates:
            - Path=/hello      # 浏览器输入 http://localhost:9091/hello 路由到 provider01/hello
            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
        - id: host_route
          uri: http://www.ityouknow.com   #目标服务地址
          predicates:
            - Path=/test     # 浏览器输入 http://localhost:9091/test，路由到 http://www.ityouknow.com 地址
            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]

