server:
  port: 9091
spring:
  application:
    name: getway

  redis:
    host: localhost
    port: 6379
    password: jl2012
    database: 1

  cloud:
    consul:
      host: 192.168.85.128  # linux
      port: 8500
      discovery:  #注册到consul的服务名称
        service-name: ${spring.application.name}
        hostname: 192.168.85.128
        health-check-path: /health  # 健康检测的url，如果不配置，健康检测一定失败
        health-check-interval: 10s   # 健康检测时间间隔
        heartbeat:
          enabled: true  # 坑所在， springboot2.x 这个一定要开
        prefer-ip-address: true #  表示注册时使用IP而不是hostname

    gateway:
      routes:
        - id: host_route2
          uri: lb://provider01  #目标服务地址
          predicates:
            - Path=/hello      # 浏览器输入 http://localhost:9091/hello 路由到 provider01/hello
            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
        - id: host_route
          uri: http://www.ityouknow.com   #目标服务地址
          predicates:
            - Path=/test     # 浏览器输入 http://localhost:9091/test，路由到 http://www.ityouknow.com 地址
            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]

