# 端口
linux: 192.168.85.128
server:
  port: 8771
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: provider01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_consul?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  cloud:
    consul:
      host: ${linux}
      port: 8500
      discovery: #注册到consul的服务名称
        service-name: ${spring.application.name}
        hostname: ${linux}
        health-check-path: /health  # 健康检测的url，如果不配置，健康检测一定失败
        health-check-interval: 10s   # 健康检测时间间隔
        heartbeat:
          enabled: true  # 坑所在， springboot2.x 这个一定要开
        prefer-ip-address: true # 表示注册时使用IP而不是hostname


  rabbitmq: #对于rabbitMQ的支持
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # ------- 消息确认配置项 --------
    # 开启confirms 回调
    publisher-confirms: true
    # 开启return 回调
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual  # 开启手动确认消息是否被消费模式
#        retry:
#          enabled: true  # 开启消费者重试
#          max-attempts: 3  # 3次

  redis:
    host: localhost
    port: 6379
    password: jl2012
    database: 1


  # 修改es健康检查地址
  elasticsearch:
    rest:
      uris:  ["http://192.168.85.128:9200"]


#控制台打印sql日志
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml   #指定mapper.xml位置

# 日志输出水平
logging:
  config: classpath:logback-spring.xml
  level:
    root: info

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

xxl:
  job:
    admin:
      addresses: http://localhost:8181/xxl-job-admin
    accessToken:
    executor:
      appname: test   #执行器名称
      address:
      ip:
      port: 9999
      logpath:
      logretentiondays: 3
