# 端口
server:
  port: 8771
spring:
  application:
    name: provider01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gen_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: 123456

  cloud:
    consul:
      host: 192.168.85.128
      port: 8500
      discovery: #注册到consul的服务名称
        service-name: ${spring.application.name}
        hostname: 192.168.85.128
        health-check-path: /health  # 健康检测的url，如果不配置，健康检测一定失败
        health-check-interval: 10s   # 健康检测时间间隔
        heartbeat:
          enabled: true  # 坑所在， springboot2.x 这个一定要开
        prefer-ip-address: true # 表示注册时使用IP而不是hostname


  rabbitmq: #对于rabbitMQ的支持
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # ------- 消息确认配置项 --------
    # 确认消息已发送到交换机
    publisher-confirms: true
    # 确认消息已发送队列
    publisher-returns: true

  redis:
    host: localhost
    port: 6379
    password: jl2012
    database: 0

#控制台打印sql日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml   #指定mapper.xml位置

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

