server:
  port: 8772
spring:
  application:
    name: comsumer
  main:
    allow-bean-definition-overriding: true #允许存在多个Feign调用相同Service的接口

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_consul?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  cloud:
    consul:
      host: ${linux}
      port: 8500
      discovery: #注册到consul的服务名称
        service-name: ${spring.application.name}
        hostname: ${linux}
        health-check-path: /health  # 健康检测的url，如果不配置，健康检测一定失败
        health-check-interval: 10s   # 健康检测时间间隔
        heartbeat:
          enabled: true  # 心跳   坑所在，springboot2.x 这个一定要开
        prefer-ip-address: true # 表示注册时使用IP而不是hostname


# 调用服务提供者服务名称  ribbon 时用到
provider: provider01

feign:
  hystrix:
    enabled: true

#暴露hystrix，stream端点:
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置随机
provider01:   # 表示作用哪个服务
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

linux: 192.168.85.128